<a href="https://colab.research.google.com/github/RoslikDima/RoslikDima/blob/main/Middle%2B%2B%2B_Polars.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import pandas as pd

# Создаем серию с целыми числами и пропуском
s = pd.Series([1, 2, None, 4])
print(s.dtype)  # float64! Единица превратилась в 1.0

float64

In [47]:
# Теперь целые числа остаются целыми, а None — это нормальный null!
s_arrow = pd.Series([1, 2, None, 4], dtype="int64[pyarrow]")
print(s_arrow)
# 0       1
# 1       2
# 2    <NA>
# 3       4
# dtype: int64[pyarrow]

0       1
1       2
2    <NA>
3       4
dtype: int64[pyarrow]

In [51]:
cities = pd.Series(["Москва", "Казань", "СПб"], dtype="string[pyarrow]")
cities

0    Москва
1    Казань
2       СПб
dtype: string

In [52]:
status = pd.Series(["new", "delivered", "new", "delivered"], dtype="category")
status

0          new
1    delivered
2          new
3    delivered
dtype: category
Categories (2, object): ['delivered', 'new']

In [53]:
df = pd.DataFrame({"a": [1, 2, 3], "b": [10, 20, 30]})
sub_df = df[df["a"] > 1]
sub_df["b"] = 999  # <- тут вылетало страшное SettingWithCopyWarning

/tmp/ipykernel_1718/604211008.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [54]:
import pandas as pd

data = {
    "user_id": [101, 102, None, 104],
    "status": ["active", "banned", "active", "active"],
    "city": ["Москва", "Самара", "Казань", "Москва"]
}